name: Docker
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up docker build
        uses: docker/setup-buildx-action@v1

      - name: Login to dockerhub
        uses: docker/login-action@v2 
        with:  
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: true 
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Run container
        run: docker run -d -p 8080:8080 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest

        
