name: Simple Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle 
        run: ./gradlew Build

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with: 
          image: docker-hub-repo/image-name
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}




